### ISSUE TITLE
How to install the snap version?

### ISSUE THREAD

**Issue by Adarah** [RBornat/jape#11]
I tried installing jape on Fedora 34 (KDE) in my `/opt` directory, but ran into problems. I skimmed around the project files and found a recent commit which seems to add snap support. How do I install this tool via snap? I couldn't find any snaps registered under the name `jape` in canonical's snap store.

**Comment by RBornat** [comment]
I built a snap, but something in the jre (I think) was doing amazing stuff with memory slices. I asked a question on the snapchat forum, but got zero replies, so I'm not trying to build a snap any more.

As to installing it in /opt: I haven't tried that. I think it will work if you put it in your home directory somewhere, but I've only tested it on ubuntu. Please try that and tell me if it works.
