### ISSUE TITLE
9.1.0d doesn't start under MacOS

### ISSUE THREAD

**Issue by RBornat** [RBornat/jape#13]
Can you give me any more details? Like OS? Is it another spaces in user name problem?

**Comment by RBornat** [comment]
My own experiment seems to show that it is not. But perhaps it is a java problem. Is there anything in the Console? (Run Console.app, search for jape; then try to start jape).

**Comment by RBornat** [comment]
I think if you choose Preferences under the Jape menu it forces the Windows menu to appear, and you can see what is in the Jape console log ...

**Comment by talia1523** [comment]
hello, i've been experiencing this problem, i tried to search jape in the console and nothing came up. there is no preferences option under the jape menu that i have, the only thing i can do is 'hide' it

**Comment by talia1523** [comment]
sorry actually i can access preferences, the only thing i can do from there is change the font. the jape window still doesn't appear

**Comment by RBornat** [comment]
but do you see a Windows menu?

**Comment by talia1523** [comment]
no

**Comment by talia1523** [comment]
i tried downloaded the 9.0.12 version that required me to have java, i downloaded and installed java 9 but jape wouldn't run then either because it says i do not have java installed

**Comment by talia1523** [comment]
*downloading

**Comment by RBornat** [comment]
Which version of MacOS are you running?

**Comment by talia1523** [comment]
10.13.6

**Comment by RBornat** [comment]
Where have you installed it? Can you run Jape from the .dmg file (i.e not installed anywhere)? I just did that successfully on a High Sierra machine.

**Comment by talia1523** [comment]
no, unfortunately that doesn't work either

**Comment by talia1523** [comment]
hey, just wanted to let you know that it works now, i had to force quit jape from the activity monitor and then when i opened it again it worked

**Comment by RBornat** [comment]
When you say it works, do you mean it works from the dmg? Or works from where you installed it?

**Comment by RBornat** [comment]
Closed for lack of information from complainant.
