### ISSUE TITLE
Crash with 9.1.1

### ISSUE THREAD

**Issue by haz** [RBornat/jape#14]
Latest seems to crash (consistently) on some operations. Attaching the log, and here's a screenshot:

![image](https://user-images.githubusercontent.com/225019/138320761-8d3dbbf7-0214-4a92-8803-c986e511f857.png)

[Jape console log 2021-10-21 at 12-39-11 EDT.txt](https://github.com/RBornat/jape/files/7391479/Jape.console.log.2021-10-21.at.12-39-11.EDT.txt)

**Comment by RBornat** [comment]
Yup. It’s a display bug. Thought I’d fixed it in 9.1.1 but I’d only chased it into the long grass. Egg on my face. Working on it now. 

Richard

**Comment by haz** [comment]
The grass grows deep ;). Thanks @RBornat !
