### ISSUE TITLE
Jape doesn't render the new conjecture prompt correctly

### ISSUE THREAD

**Issue by Cagdas94** [RBornat/jape#15]
I've noticed that the "OK" and "Cancel" buttons are cut off on version 9.1.2.

This happens on both Linux and Windows:
![image](https://user-images.githubusercontent.com/70543994/139753063-8c4b8dd7-cbca-45b0-a05f-0d4c1d40b430.png)
![image](https://user-images.githubusercontent.com/70543994/139753184-971a86d5-afbc-4a41-97b1-5336df57aaaf.png)

However, it's fine on MacOS:
![image](https://user-images.githubusercontent.com/70543994/139753320-61154a4c-1f23-4b63-bd0e-8a5b30342e2d.png)

No clue why this happens. It doesn't affect the usability in any way but it's just annoying.

**Comment by RBornat** [comment]
Thanks for the bug report. Looks like a Java bug (sigh). I’ll look at it today. 

Richard

**Comment by RBornat** [comment]
Fixed (and even tidied up the Text Command window on the way). Thanks very much for the bug report.

Version 9.1.3 released.
