### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by AsadGulbahar** [RBornat/jape#17]
I tried to open the I2L.jt file and get this error.

![Screenshot (287)](https://user-images.githubusercontent.com/95498999/148990177-75db8fbf-2e8b-4d26-83d3-5c47cae9ed17.png)

**Comment by RBornat** [comment]
You are opening an outdated version of the examples directory. LETLISTMATCH has been retired. Use the examples directory that came with the Jape you downloaded.

Richard

**Comment by AsadGulbahar** [comment]
It works now. Thank you for your help.
