### ISSUE TITLE
Multiple premises do not show up on separate lines

### ISSUE THREAD

**Issue by AsadGulbahar** [RBornat/jape#18]
On the macOS version of Jape, multiple premises are displayed on separate lines whereas on Windows, multiple premises are displayed on the same line.

![Screenshot (289)](https://user-images.githubusercontent.com/95498999/149013529-493df4d3-9733-4cf7-9522-fe1687ad85e0.png)

**Comment by RBornat** [comment]
Depends on the width of the window. And some logics specify one premise per line.
