### ISSUE TITLE
Problem with MacOs distribution and Linux Ubuntu

### ISSUE THREAD

**Issue by komolcia** [RBornat/jape#19]
When using Jape on MacOs
<img width="497" alt="image" src="https://user-images.githubusercontent.com/58554458/197272083-831791ef-3c15-4c29-a4f8-5cbebace91e5.png">
When using Linux Ubuntu
http://echolocation.wikidot.com/jape-installation

**Comment by RBornat** [comment]
More history please. Which .jt files were you reading from. You can’t read from arbitrary.j files:you must load a theory. 

Richard

**Comment by komolcia** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/58554458/197274432-c20f5385-75a5-478e-a299-6e1e37f5fc28.png">
 I tried to open this file and still it doesn't work [https://inf.ug.edu.pl/~amb/logika-lab/Jape/lab01-int.j](https://inf.ug.edu.pl/~amb/logika-lab/Jape/lab01-int.j)

**Comment by komolcia** [comment]
Never mind. I see now that I have to load theory first then arbitrary files. At University they somehow managed it without first loading theory.
