### ISSUE TITLE
Example file set_syntax.j and set_russell.j can not open 

### ISSUE THREAD

**Issue by 123321abccba1** [RBornat/jape#22]
I can not open those two file in jape,
I use latest version 9.1.7 in Windows 10 x64

![image](https://github.com/RBornat/jape/assets/47651072/0a907b9b-27ca-4729-816b-5aa43b874c95)

**Comment by luanfg** [comment]
Having the same problem when trying to load any saved formulae on windows 9.1.7.

**Comment by RBornat** [comment]
To both of you: you cannot load just any file into jape. You have first to load a theory — for Garcia it is probably I2L.jt; for 12aa it will be sets.jt. Sent from my iPhoneOn 17 Sep 2023, at 19:16, Luan Garcia ***@***.***> wrote:﻿
Having the same problem when trying to load any saved formulae on windows 9.1.7.

**Comment by luanfg** [comment]
You are completely right. Sorry about that!
