### ISSUE TITLE
Obscure Jape Error Message

### ISSUE THREAD

**Issue by haz** [RBornat/jape#24]
Seems as though the latest version of Jape casts some "obscure errors" whenever a sequent including quantifiers (in natural deduction) is recorded. This is the first window...

![image](https://github.com/RBornat/jape/assets/225019/ca9635f9-1dd6-4161-9c7f-8a98b3ed382e)

And after hitting `Ok`, this is what comes up:

![image](https://github.com/RBornat/jape/assets/225019/15247c1f-4c0f-4a25-ba35-68ca89930c42)

Best I can tell, the `Continue` option saves the proof and things proceed as normal. This can be reproduced by...

1. installing the latest (tried only on windows)
2. loading natural deduction
3. proving one of the FOL conjectures
4. closing it and hitting record

**Comment by RBornat** [comment]
Oh dear. That was my Christmas fix. Inadequately tested. Will chase up asap. RSent from my iPhoneOn 6 Oct 2023, at 19:45, Christian Muise ***@***.***> wrote:﻿
Seems as though the latest version of Jape casts some "obscure errors" whenever a sequent including quantifiers (in natural deduction) is recorded. This is the first window...

And after hitting Ok, this is what comes up:

Best I can tell, the Continue option saves the proof and things proceed as normal. This can be reproduced by...

installing the latest (tried only on windows)
loading natural deduction
proving one of the FOL conjectures
closing it and hitting record

**Comment by haz** [comment]
No rush, thank you @RBornat !

**Comment by RBornat** [comment]
fixed in 9.1.8
