### ISSUE TITLE
Jape crush in macOS

### ISSUE THREAD

**Issue by suimingpro** [RBornat/jape#25]
Jape running in my MacBook is very easy to crush, I don't know how to trigger it, here are the Logs:

https://gist.github.com/123321abccba1/4150a9cb28dc01a3fbcf2dd908f12ed4

**Comment by 123321abccba1** [comment]
Jape version: 9.1.8

**Comment by RBornat** [comment]
That bug report tells me that Java has crashed. I’m not able to see any information about what you were doing when it crashed. Sorry. Richard Sent from my iPhoneOn 27 Oct 2023, at 19:50, 123321abccba1 ***@***.***> wrote:﻿
Jape running in my MacBook is very easy to crush, I don't know how to trigger it, here are the Logs:
https://gist.github.com/123321abccba1/4150a9cb28dc01a3fbcf2dd908f12ed4

**Comment by 123321abccba1** [comment]
Here are the jape Logs, When I finish my proof and close the windows Jape will ask me to record the proof but when I click record bottom proof window does not close. and them  Jape crush.

https://gist.github.com/123321abccba1/fb225d2a42dde619ee4aa93a9bc849f7

**Comment by haz** [comment]
Hey @123321abccba1  -- we really need to see the behaviour in action. Can you please record a Loom (or similar) video, and start it from before you open Jape up until the point of the crash? Thanks.

**Comment by 123321abccba1** [comment]
https://drive.google.com/file/d/13eEqjQ_gH44c5w7dEhzAcwgv-YoavNSK/view?usp=drive_link

**Comment by RBornat** [comment]
Sorry. I don’t have anything to do with Google. Sent from my iPhoneOn 28 Oct 2023, at 03:18, 123321abccba1 ***@***.***> wrote:﻿
https://drive.google.com/file/d/13eEqjQ_gH44c5w7dEhzAcwgv-YoavNSK/view?usp=drive_link

**Comment by haz** [comment]
> https://drive.google.com/file/d/13eEqjQ_gH44c5w7dEhzAcwgv-YoavNSK/view?usp=drive_link

Sharing drive links can be a major security issue. If that's a video, you can upload it to YouTube as an unlisted video and share the link there.

**Comment by 123321abccba1** [comment]
https://youtu.be/rqzjffDUxYs

**Comment by haz** [comment]
Thanks, @123321abccba1 .

@RBornat : As the deadline to the next assignment draws closer, we're seeing a bump in reports about this funny-looking bug. Anything I can do to help guide the students through generating more logging information to help narrow down what's happening? Seems to be only an issue that cropped up with this latest release.

Thanks!

**Comment by RBornat** [comment]
Bad luck for your students and for me: the first bug report reached me in hospital. I don’t doubt I’ll be able to fix it, but it will be a couple of days at least. As it seems to be to do with closing proofs, would you accept screenshots of completed proofs?I haven’t dealt with your bugs very well over the last year. I’m ashamed. Richard Sent from my iPhoneOn 30 Oct 2023, at 16:27, Christian Muise ***@***.***> wrote:﻿
Thanks, @123321abccba1 .
@RBornat : As the deadline to the next assignment draws closer, we're seeing a bump in reports about this funny-looking bug. Anything I can do to help guide the students through generating more logging information to help narrow down what's happening? Seems to be only an issue that cropped up with this latest release.
Thanks!

**Comment by haz** [comment]
I'm so sorry to hear, @RBornat !

Of course, we'll find a work-around for the course assessments -- we already have screenshots as a backstop.

**Comment by RBornat** [comment]
So the one youtube video I've been sent is a report of zombie windows, not a crash (show a proof that you've already made, and you can't close it). Fixed that. Could you encourage your students to report a crash, if they know how to generate one? All I have is this text, which is difficult to work from:

> Here are the jape Logs, When I finish my proof and close the windows Jape will ask me to record the proof but when I click record bottom proof window does not close. and them Jape crush.

Presumably 'crush' means 'crash'. I haven't yet managed to provoke a crash.

Richard

**Comment by haz** [comment]
Thanks, @RBornat !

My understanding is that it's a zombie window that's primarily the problem and is present in 9.1.8. Do you have an unreleased fix, or are you referring to a previous version?

@123321abccba1 : If you were observing a true crash -- i.e., the problem quits unexpectedly -- then we'd need to see a video capturing that behaviour.

**Comment by RBornat** [comment]
This issue is fixed by the release of version 9.1.8a. The 'crush' I know nothing about.
