### ISSUE TITLE
Add CI integration?

### ISSUE THREAD

**Issue by teymour-aldridge** [RBornat/jape#6]

**Comment by RBornat** [comment]
Pardon? What does this mean?

R

**Comment by teymour-aldridge** [comment]
Sorry!
CI (continuous integration) integrates into git and does useful things, like running tests for a project on every commit (and pull request). It can also automatically build and publish binaries whenever a release is published as well as run a code linter (which checks for things like ununsed items, overly long code lines, etc).

**Comment by RBornat** [comment]
Tests for a UI project are hard to imagine ...

R

**Comment by teymour-aldridge** [comment]
I think you can test UI projects! There are lots of tools for this sort of stuff. I don't know what Jape uses for the UI (beyond Java) but I'd imagine there's a test framework – but the OCaml stuff can definitely be tested.
It's still useful for code style, auto publishing stuff, etc.

**Comment by RBornat** [comment]
I'm really not interested. All of the problems in Jape over the last two years have been installation issues.
