### ISSUE TITLE
Not support for MacOS big sur

### ISSUE THREAD

**Issue by charliechen233** [RBornat/jape#7]
I have recently updated the latest version of MacOS Big Sur. However, I can not open JAPE in it.

**Comment by RBornat** [comment]
Oh dear. What version of Java have you installed? What happens when you try to run jape?

Richard

**Comment by RBornat** [comment]
It seems that Apple has changed the behaviour of the JAVA_HOME variable that is used to point to Java. So I think that perhaps Java doesn’t run. Can you check? (Run ‘java -version’ in a Terminal window.)

Richard

**Comment by charliechen233** [comment]
Hi, the java version is 11.0.8. My macOS is 11.0.1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RBornat** [comment]
When you say it won’t run, have you tried the ctrl-press, choose Open from the pop-up menu technique? You have to persuade Big Sur to trust it, all over again. 

Richard

**Comment by charliechen233** [comment]
I tried the Ctrl press, but still did not work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RBornat** [comment]
So what happens? What error messages? What different mechanisms have you tried? I can’t do anything with “won’t run”. I don’t have a machine that can run Big Sur. 

Richard

**Comment by RBornat** [comment]
In particular, did _anything_ happen?

Richard

**Comment by charliechen233** [comment]
It just crashed without any error messages. It seems that JAPE isn’t compatible to Big Sur.

**Comment by RBornat** [comment]
please run the Console app to look at the system logs. Somewhere in there there will be messages sent from jape while it is trying to start up. Messages like this

default	13:58:31.851609+0000	syslog	[11027][universalJavaApplicationStub] [StubDir] /Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/MacOS
default	13:58:31.893901+0000	syslog	[11027][Jape] [PlistStyle] Apple
default	13:58:32.020371+0000	syslog	[11027][Jape] [JavaRequirement] JVM minimum version: 1.6+
default	13:58:32.030246+0000	syslog	[11027][Jape] [JavaRequirement] JVM maximum version:
default	13:58:32.081465+0000	syslog	[11027][Jape] [Language] en_GB
default	13:58:33.060431+0000	syslog	[11027][Jape] [JavaSearch] Checking for $JAVA_HOME ...
default	13:58:33.071974+0000	syslog	[11027][Jape] [JavaSearch] ... found JAVA_HOME with value /Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home
default	13:58:33.632749+0000	syslog	[11027][Jape] [JavaCommand] '/Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home/bin/java'
default	13:58:33.801348+0000	syslog	[11027][Jape] [JavaVersion] 11.0.5 / 11000005
default	13:58:33.812577+0000	syslog	[11027][Jape] [WorkingDirectory] /Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build
default	13:58:33.824115+0000	syslog	[11027][Jape] [Exec] "/Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home/bin/java" -cp ".:/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Resources/Java/Jape.jar" -splash:"/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Resources/" -Xdock:icon="/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Resources/Jape.icns" -Xdock:name="Jape" '-Duk.org.jape.AppPackage=/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app' '-DNSHighResolutionCapable=true' '-Dapple.awt.antialiasing=true' '-Dapple.laf.useScreenMenuBar=true' '-Dapple.awt.rendering=quality' '-Dapple.awt.showGrowBox=true'  uk.org.jape.Jape


Just run Console, watch the messages that come up while you try to start jape with ctrl-press and Open.

Then send me the messages. (They might not look like the above ...)

Richard

**Comment by RBornat** [comment]
Can you send any screenshots?

R

**Comment by charliechen233** [comment]
[Graphical user interface, text, application, email  Description automatically generated]
Is it like this?

**Comment by RBornat** [comment]
I think the problem may be Java 11. Big Sur doesn’t seem to like it. Install Java 15?

Richard

**Comment by charliechen233** [comment]
I installed it, but still does not work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RBornat** [comment]
Is jape on the desktop when you try to run it? Have you looked at the Console messages, as I requested?

Richard

**Comment by charliechen233** [comment]
JAPE is on application, and. I sent you the screen shot of console yesterday.

**Comment by RBornat** [comment]
I didn’t get the screenshot. Could you send it to richard@bornat.me.uk? The Console messages are even more important. 

R

**Comment by haz** [comment]
Does this happen to be resolved with 9.0.12b? If so, any chance we can get the other two assets for that release? (Linux & Windows installations)

Thanks!

**Comment by RBornat** [comment]
I believe it is resolved. The only difference between a and b is the MacOS-specific launch mechanism for Jape. So the a version for Windows and Linux is what you need. 

If that’s confusing at all, or inconvenient, let me know and I’ll delete the a version and add the bits to the b version. 

Richard

**Comment by haz** [comment]
Ah, ok. Not a problem at all -- just wanted to be sure I was including the correct info in the course tutorial for getting things up and going. Thanks for the details!

**Comment by haz** [comment]
Just had a TA give 9.0.12b a go -- only snag they ran into is installing it into their `Documents` folder and ran into permissions problems when trying to load a theory from the `examples` directory. They had to move the Jape folder back up to their user directory before it would work.

**Comment by RBornat** [comment]
That’s right. Nothing I can do about that. Documents, Desktop : don’t use. 

R

**Comment by haz** [comment]
Reckon this can be closed...

**Comment by RBornat** [comment]
Closed. Fixed long ago.
